repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        args: ['--count', '--select', 'E101,E11,E111,E112,E113,E121,E122,E123,E124,E125,E126,E127,E128,E129,E131,E133,E20,E211,E231,E241,E242,E251,E252,E26,E265,E266,E27,E301,E302,E303,E304,E305,E306,E401,E471,E502,E701,E711,E712,E713,E714,E722,E731,E901,E902,F822,F823,W191,W291,W292,W293,W391,W601,W602,W603,W604,W605,W690', "--ignore=E203"]
        exclude: ".*(.fits|.fts|.fit|.txt|tca.*|extern.*|.rst|.md|.svg|versioneer.py)$"
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
        exclude: ".*(.fits|.fts|.fit|.txt|tca.*|extern.*|.rst|.md|__init__.py|.svg)$"
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: ".*(.fits|.fts|.fit|.txt|tca.*|extern.*|.rst|.md|.svg)$"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
        exclude_types: ["jupyter"]
    -   id: end-of-file-fixer
        exclude_types: ["jupyter"]
    -   id: trailing-whitespace
        exclude_types: ["jupyter"]
    -   id: check-docstring-first
        exclude_types: ["jupyter"]
    -   id: check-merge-conflict
        exclude_types: ["jupyter"]
    -   id: check-added-large-files
        args: [--maxkb, "2000"]
    -   id: mixed-line-ending
        exclude_types: ["jupyter"]
        args: [--fix=lf]
# this is good but fails with metaclasses
# so just run every now and then
# -   repo: https://github.com/asottile/dead
#     rev: v1.4.0
#     hooks:
#     -   id: dead
