name: ml
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - mamba
  - pre-commit
  - ca-certificates
  - certifi
  - openssl
  - pytest
  - xgboost
  - bayesian-optimization
  - scikit-optimize
  - scipy
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
    - stable_baselines3
    - optuna
    - pathos
    - pybats
