[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
black formatter
/(
    \.eggs
    \.git
    \.hgg
    \.mypy_cache
    \.tox
    \.venv
    \_build
    \buck-out
    \build
    dist
)
'''
